apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongo-db
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-mongo-db
  template:
    metadata:
      labels:
        app: my-mongo-db
    spec:
      containers:
      - image: mongo
        name: my-mongo-db
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
        - name: mongo-data
          hostPath:
           path: local