apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongo-express
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-mongo-express
  template:
    metadata:
      labels:
        app: my-mongo-express
    spec:
      containers:
      - image: mongo-express
        name: my-mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "admin"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "password"
        - name: ME_CONFIG_MONGODB_SERVER
          value: "my-mongo-db"